name: MacOs Runner Test
on:
  workflow_dispatch:
  
jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Hello World
        run: echo "Hello World"
